### ISSUE TITLE
CSS syntax colour scheme broken

### ISSUE THREAD

**Issue by harrync** [P233/Syntax-highlighting-for-Sass#67] opened 2017-11-27 12:19 UTC
Latest version is leaving the CSS display broken, with incorrect and inconsistent syntax highlighting.

Screenshot attached.
![sublime_text_2017-11-27_12-19-04](https://user-images.githubusercontent.com/1128430/33266364-3f40c2a2-d36d-11e7-8b4e-b249cdd8f4d6.png)

**Comment by P233** [comment] 2017-11-27 13:06
I have pushed an update to highlight the property-name a few hours ago. Could you upgrade this package and test again? Thanks!

Sorry I'll close this issue as this is a duplicate of #65

**Closed by P233** 2017-11-27 13:06 UTC

**Comment by harrync** [comment] 2017-11-27 13:37
Hiya,

That appears to have fixed the issue. Many thanks!

Cheers
Harry
